title = "vcfanno configuration file"

[[annotation]]
file = "gnomad_2.1.1/gnomad.exomes.r2.1.1.sites.vcf.bgz"
fields = ["AF", "AF_popmax"]
ops = ["self", "self"]
names = ["GNOMADAF", "GNOMADAF_popmax"]

[[annotation]]
file = "spidex/hg19_spidex.tsv.gz"
names = ["SPIDEX"]
ops = ["mean"]
columns = [6]