output: "{{PLUMBER_PIPELINE_HOME}}/config/output_files.yaml"
resources: "{{PLUMBER_PIPELINE_CONFIG}}/assets/resources.yaml"

filter_vcf:
  snv_soft_filter: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_soft_filter_uppsala_vep105.yaml"
  snv_soft_filter_umi: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_soft_filter_umi_vep105.yaml"
  snv_hard_filter: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_hard_filter_uppsala_vep105.yaml"
  snv_hard_filter_umi: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_hard_filter_umi_vep105.yaml"
  snv_hard_filter_purecn: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_hard_filter_purecn.yaml"
  cnv_hard_filter_amp: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_hard_filter_cnv_amp.yaml"
  cnv_hard_filter_loh: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_hard_filter_cnv_loh.yaml"
  germline: "{{PLUMBER_PIPELINE_HOME}}/config/filters/config_hard_filter_germline_vep105.yaml"

hotspot_annotation:
  chr_translation_file: "{{PLUMBER_PIPELINE_HOME}}/config/reports/hotspot_report.chr.translation.hg19"

hotspot_report:
  chr_translation_file: "{{PLUMBER_PIPELINE_HOME}}/config/reports/hotspot_report.chr.translation.hg19"
  report_config: "{{PLUMBER_PIPELINE_HOME}}/config/reports/hotspot_report.yaml"

multiqc:
  reports:
    DNA:
      config: "{{PLUMBER_PIPELINE_HOME}}/config/reports/multiqc_config_dna.yaml"
    DNA_umi:
      config: "{{PLUMBER_PIPELINE_HOME}}/config/reports/multiqc_config_dna.yaml"
    RNA:
      config: "{{PLUMBER_PIPELINE_HOME}}/config/reports/multiqc_config_rna.yaml"
