version: 1
pipelines:
  - name: nf-core/raredisease
    version: "2.4.0"
    engine: nextflow
    profiles:
      - ./nextflow/nf-core/rv.config
    config_files:
      - ./nextflow/nf-core/raredisease/raredisease.config
    param_files:
      - ./nextflow/nf-core/raredisease/params.yaml
    assets:
      - ./nextflow/nf-core/assets/raredisease
      - ./nextflow/nf-core/assets/GRCh38_chrY.interval_list
      - ./nextflow/nf-core/assets/GRCh38_chr1-chr22chrXchrYchrM.interval_list
      - ./nextflow/nf-core/assets/variant_consequences.txt
  - name: genomic-medicine-sweden/Twist_Solid
    version: "0.14.0"
    engine: snakemake
    executor:
      name: python
      version: "3.9"
    environment:
      PLUMBER_REFERENCE_DATA: /storage/userdata/references/homo_sapiens/twist-solid
    args:
      config:
        - PROJECT_DESIGN_DATA=$PLUMBER_REFERENCE_DATA
        - PROJECT_PON_DATA=$PLUMBER_REFERENCE_DATA
        - PROJECT_REF_DATA=$PLUMBER_REFERENCE_DATA
    profiles:
      - name: slurm_hg19_clinical
        profile: ./hydra-genetics/twist-solid/0.14.0/profiles/slurm_hg19_clinical
        config_files:
          - ./hydra-genetics/twist-solid/0.14.0/configs/config.yaml
          - ./hydra-genetics/twist-solid/0.14.0/configs/resources_clinical.yaml
      - name: slurm_hg19_research
        profile: ./hydra-genetics/twist-solid/0.14.0/profiles/slurm_hg19_research
        config_files:
          - ./hydra-genetics/twist-solid/0.14.0/configs/config.yaml
          - ./hydra-genetics/twist-solid/0.14.0/configs/resources_research.yaml
  - name: genomic-medicine-sweden/Twist_Solid
    version: "v0.23.0"
    engine: snakemake
    environment:
      PLUMBER_REFERENCE_DATA: /storage/userdata/references/homo_sapiens/twist-solid
    args:
      config:
        - PROJECT_DESIGN_DATA=$PLUMBER_REFERENCE_DATA
        - PROJECT_PON_DATA=$PLUMBER_REFERENCE_DATA
        - PROJECT_REF_DATA=$PLUMBER_REFERENCE_DATA
        - PLUMBER_PIPELINE_CONFIG=$PLUMBER_PIPELINE_CONFIG
        - PLUMBER_PIPELINE_HOME=$PLUMBER_PIPELINE_HOME
    executor:
      name: python
      version: "3.10"
    assets:
        - ./hydra-genetics/twist-solid/0.23.0/configs/resources.yaml
    profiles:
      - name: slurm_hg19_clinical
        profile: ./hydra-genetics/twist-solid/0.23.0/profiles/slurm
        config_files:
          - $PLUMBER_PIPELINE_HOME/config/config.yaml
          - $PLUMBER_PIPELINE_HOME/config/config.data.hg19.yaml
          - ./hydra-genetics/twist-solid/0.23.0/configs/config.hg19.yaml
          - ./hydra-genetics/twist-solid/0.23.0/configs/resources.clinical.yaml
      - name: slurm_hg19_research
        profile: ./hydra-genetics/twist-solid/0.23.0/profiles/slurm
        config_files:
          - $PLUMBER_PIPELINE_HOME/config/config.yaml
          - $PLUMBER_PIPELINE_HOME/config/config.data.hg19.yaml
          - ./hydra-genetics/twist-solid/0.23.0/configs/config.hg19.yaml
          - ./hydra-genetics/twist-solid/0.23.0/configs/resources.research.yaml
