version: 1
pipelines:
  - name: nf-core/raredisease
    engine: nextflow
    version: "2.2.0"
    profiles:
      - ./nextflow/nf-core/rv.config
    config_files:
      - ./nextflow/nf-core/raredisease/raredisease.config
    param_files:
      - ./nextflow/nf-core/raredisease/params.yaml
    assets:
      - ./nextflow/nf-core/assets/raredisease
  - name: genomic-medicine-sweden/Twist_Solid
    engine: snakemake
    version: "0.14.0"
    profiles:
      - ./hydra-genetics/twist-solid/0.14.0/profiles/slurm_hg19_clinical
      - ./hydra-genetics/twist-solid/0.14.0/profiles/slurm_hg19_research
    config_files:
      - ./hydra-genetics/twist-solid/0.14.0/configs/config.yaml
      - ./hydra-genetics/twist-solid/0.14.0/configs/resources_clinical.yaml
      - ./hydra-genetics/twist-solid/0.14.0/configs/resources_research.yaml
