version: 1
pipelines:
  - name: nf-core/raredisease
    engine: nextflow
    version: "2.4.0"
    profiles:
      - ./nextflow/nf-core/rv.config
    config_files:
      - ./nextflow/nf-core/raredisease/raredisease.config
    param_files:
      - ./nextflow/nf-core/raredisease/params.yaml
    assets:
      - ./nextflow/nf-core/assets/raredisease
      - ./nextflow/nf-core/assets/GRCh38_chrY.interval_list
      - ./nextflow/nf-core/assets/GRCh38_chr1-chr22chrXchrYchrM.interval_list
      - ./nextflow/nf-core/assets/variant_consequences.txt
  - name: genomic-medicine-sweden/Twist_Solid
    engine: snakemake
    version: "0.14.0"
    executor:
      name: python
      version: "3.9"
    profiles:
      - ./hydra-genetics/twist-solid/0.14.0/profiles/slurm_hg19_clinical
      - ./hydra-genetics/twist-solid/0.14.0/profiles/slurm_hg19_research
    config_files:
      - ./hydra-genetics/twist-solid/0.14.0/configs/config.yaml
      - ./hydra-genetics/twist-solid/0.14.0/configs/resources_clinical.yaml
      - ./hydra-genetics/twist-solid/0.14.0/configs/resources_research.yaml
  - name: genomic-medicine-sweden/Twist_Solid
    engine: snakemake
    version: "0.23.0"
    executor:
      name: python
      version: "3.10"
    profiles:
      - ./hydra-genetics/twist-solid/0.23.0/profiles/slurm
    config_files:
      - ./hydra-genetics/twist-solid/0.23.0/configs/config.yaml
      - ./hydra-genetics/twist-solid/0.23.0/configs/resources_clinical.yaml
      - ./hydra-genetics/twist-solid/0.23.0/configs/resources_research.yaml
