jobs: 500
keep-going: true
restart-times: 2
rerun-incomplete: true
show-failed-logs: true

use-conda: false
use-singularity: true
singularity-prefix: /storage/userdata/singularity_cache
singularity-args: --bind /storage --bind /scale --bind $HOME --bind /scratch --bind /tmp

cluster: sbatch --parsable --time={resources.time} --cpus-per-task={resources.threads} --mem-per-cpu={resources.mem_per_cpu} --partition={resources.partition} --nodelist=${{SLURM_JOB_NODELIST:-vs1513,vs1514}} --job-name=twist-solid.{rule} --output=slurm_logs/{rule}_%j.out
cluster-status: slurm-status.py
cluster-cancel: scancel

configfiles:
  - config/config.yaml
  - config_0.9.0/config.yaml

groups:
  - fuseq_wes=fusions_fuseq_wes
  - fuseq_wes=fusions_filter_report_fuseq_wes
  - fuseq_wes=_copy_fuseq_wes

  - manta=cnv_sv_manta_config_t
  - manta=cnv_sv_manta_run_workflow_t
  - manta=_copy_manta_vcf

  - cnv_tsv_report=cnv_tsv_report
  - cnv_tsv_report=_copy_cnv_tsv_report_validated_pathology_purecn
  - cnv_tsv_report=_copy_cnv_tsv_report_purecn
  - cnv_tsv_report=_copy_cnv_tsv_report_validated_purecn
  - cnv_tsv_report=_copy_cnv_tsv_report_pathology_purecn
  - cnv_tsv_report=_copy_cnv_tsv_report_pathology
  - cnv_tsv_report=_copy_cnv_tsv_report_validated_pathology

  - hrd=biomarker_fix_scarhd_output
  - hrd=_copy_hrd_score_pathology_purecn
  - hrd=_copy_hrd_score_purecn
  - hrd=_copy_hrd_score_pathology

  - purecn=cnv_sv_purecn
  - purecn=cnv_sv_purecn_copy_output
  - purecn=cnv_sv_purecn_purity_file

  - multiqc=qc_multiqc
  - multiqc=_copy_multiqc_dna_html

  - gatk1=qc_gatk_get_pileup_summaries
  - gatk1=qc_gatk_calculate_contamination
  - gatk1=_copy_contamination_table

  - svdb_query=cnv_sv_svdb_query
  - svdb_query=_copy_svdb_query_pathology
  - svdb_query=_copy_svdb_query_pathology_purecn
  - svdb_query=_copy_svdb_query_purecn

  - gatk2=cnv_sv_gatk_collect_read_counts
  - gatk2=cnv_sv_gatk_denoise_read_counts
  - gatk2=cnv_sv_gatk_model_segments
  - gatk2=call_small_cnv_deletions
  - gatk2=_copy_small_cnv_deletions
  - gatk2=call_small_cnv_amplifications
  - gatk2=_copy_small_cnv_amplifications

  - gatk3=snv_indels_gatk_mutect2
  - gatk3=snv_indels_gatk_mutect2_merge_stats

  - annot1=annotation_vep
  - annot1=fix_vcf_ad_for_qci
  - annot1=_copy_qci_vcf
  - annot1=_copy_codon_snv_vcf

  - annot2=annotation_artifact_annotation
  - annot2=annotation_hotspot_annotation
  - annot2=annotation_background_annotation

  - filtering1=filtering_bcftools_filter_include_region
  - filtering1=filtering_filter_vcf
  - filtering1=annotation_add_multi_snv_in_codon
  - filtering1=_copy_exononly_hardfiltered_vcf
  - filtering1=_copy_exononly_softfiltered_vcf

  - reports1=reports_cnv_json
  - reports1=reports_merge_cnv_json
  - reports1=reports_cnv_html_report
  - reports1=_copy_cnv_html_report_pathology_purecn
  - reports1=_copy_cnv_html_report_pathology
  - reports1=_copy_cnv_html_report_purecn

  - hotspots=hotspot_report
  - hotspots=_copy_hotspot_tsv

  - tmb=snv_indels_bgzip
  - tmb=biomarker_tmb
  - tmb=_copy_tmb
  
  - bed_split=snv_indels_bed_split

group-components:
	- bed_split=50
