PROJECT_DESIGN_DATA: "/storage/userdata/references/homo_sapiens/hg19/hydra-genetics/twist-solid"
PROJECT_PON_DATA: "/storage/userdata/references/homo_sapiens/hg19/hydra-genetics/twist-solid"
PROJECT_REF_DATA: "/storage/userdata/references/homo_sapiens/hg19/hydra-genetics/twist-solid"
