---
snakefile: /storage/userdata/pipelines/Twist_Solid/0.13.0/workflow/Snakefile
configfiles:
  - /storage/userdata/pipelines/Twist_Solid/0.13.0/config/config.yaml
  - /storage/userdata/pipelines/Twist_Solid/0.13.0/config/config.data.hg19.yaml
  - /storage/userdata/pipelines/config-files/hydra-genetics/twist-solid/0.13.0/configs/config.yaml

config:
  - resources=/storage/userdata/pipelines/config-files/hydra-genetics/twist-solid/0.13.0/configs/resources_research.yaml

jobs: 500
keep-going: true
latency-wait: 60
restart-times: 2
rerun-incomplete: true
show-failed-logs: true

use-conda: false
use-singularity: true
singularity-prefix: /storage/userdata/snakemake_singularity_cache
singularity-args: --bind /storage --bind /scale --bind $HOME --bind /scratch --bind /tmp --cleanenv

cluster: sbatch --parsable --time={resources.time} --cpus-per-task={resources.threads} --mem-per-cpu={resources.mem_per_cpu} --partition={resources.partition} --job-name=twist-solid.{rule} --output=slurm_logs/{rule}_%j.out
cluster-status: ../../../../../scripts/slurm-status.py
cluster-cancel: scancel
