output: "{{TWIST_SOLID_HOME}}/config/output_files.yaml"
resources: "{{TWIST_SOLID_CONFIG}}/configs/resources.yaml"
general_report: "{{TWIST_SOLID_HOME}}/config/reports/general_report.yaml"

filter_vcf:
  snv_soft_filter: "{{TWIST_SOLID_HOME}}/config/filters/config_soft_filter_uppsala_vep105.yaml"
  snv_soft_filter_umi: "{{TWIST_SOLID_HOME}}/config/filters/config_soft_filter_umi_vep105.yaml"
  snv_hard_filter: "{{TWIST_SOLID_HOME}}/config/filters/config_hard_filter_uppsala_vep105.yaml"
  snv_hard_filter_umi: "{{TWIST_SOLID_HOME}}/config/filters/config_hard_filter_umi_vep105.yaml"
  snv_hard_filter_purecn: "{{TWIST_SOLID_HOME}}/config/filters/config_hard_filter_purecn.yaml"
  cnv_hard_filter_amp: "{{TWIST_SOLID_HOME}}/config/filters/config_hard_filter_cnv_amp.yaml"
  cnv_hard_filter_loh: "{{TWIST_SOLID_HOME}}/config/filters/config_hard_filter_cnv_loh.yaml"
  germline: "{{TWIST_SOLID_HOME}}/config/filters/config_hard_filter_germline_vep105.yaml"
  itd_hard_filter: "{{TWIST_SOLID_HOME}}/config/filters/config_hard_filter_scanitd.yaml"

hotspot_annotation:
  chr_translation_file: "{{TWIST_SOLID_HOME}}/config/reports/hotspot_report.chr.translation.hg19"

hotspot_report:
  chr_translation_file: "{{TWIST_SOLID_HOME}}/config/reports/hotspot_report.chr.translation.hg19"
  report_config: "{{TWIST_SOLID_HOME}}/config/reports/hotspot_report.yaml"

merge_cnv_json:
  annotations:
    - "{{PROJECT_DESIGN_DATA}}/GMS560/cnv/cnv_amp_genes_240307.bed"
    - "{{PROJECT_DESIGN_DATA}}/GMS560/cnv/cnv_loh_genes_240618.bed"

multiqc:
  reports:
    DNA:
      config: "{{TWIST_SOLID_HOME}}/config/reports/multiqc_config_dna.yaml"
    DNA_umi:
      config: "{{TWIST_SOLID_HOME}}/config/reports/multiqc_config_dna.yaml"
    RNA:
      config: "{{TWIST_SOLID_HOME}}/config/reports/multiqc_config_rna.yaml"
