filters:
  artifacts:
    description: "Hard filter variants found in more than 15% of the normal samples"
    expression: "(INFO:Twist_AF > 0.15)"
    soft_filter: "False"
  copy_number:
    description: "Hard filter cnvs with over 1.4 copies"
    expression: "(INFO:CORR_CN > 1.4)"
    soft_filter: "False"
  amp_gene:
    description: "Only keep variants with gene annotations"
    expression: "(!exist[[A-Za-z0-9_,-]+, INFO:Genes])"
    soft_filter: "False"
