---
latency-wait: 180
restart-times: 0
rerun-incomplete: true
show-failed-logs: true

executor: slurm
jobs: unlimited

software-deployment-method: apptainer
apptainer-prefix: /storage/userdata/snakemake_singularity_cache
apptainer-args: "--bind /storage --bind /scale --bind $HOME --bind /tmp --cleanenv"
